// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJhXkZFmdJ1IWFu9a6rwiqzRfKR8BIsHY',
    appId: '1:158686991115:web:6c4964c3e9fcb5e0c5480e',
    messagingSenderId: '158686991115',
    projectId: 'beramalbaik-90b62',
    authDomain: 'beramalbaik-90b62.firebaseapp.com',
    databaseURL: 'https://beramalbaik-90b62-default-rtdb.firebaseio.com',
    storageBucket: 'beramalbaik-90b62.firebasestorage.app',
    measurementId: 'G-E133T5XP1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3gpQON7sS6gR1CTf3S0le5WmjJN-KQ8g',
    appId: '1:158686991115:android:8cad2b2e19d3c21dc5480e',
    messagingSenderId: '158686991115',
    projectId: 'beramalbaik-90b62',
    databaseURL: 'https://beramalbaik-90b62-default-rtdb.firebaseio.com',
    storageBucket: 'beramalbaik-90b62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhCJS-kDlVBkqpTltXpj_b0Dz67qSkKik',
    appId: '1:158686991115:ios:32c094942de57187c5480e',
    messagingSenderId: '158686991115',
    projectId: 'beramalbaik-90b62',
    databaseURL: 'https://beramalbaik-90b62-default-rtdb.firebaseio.com',
    storageBucket: 'beramalbaik-90b62.firebasestorage.app',
    iosBundleId: 'com.example.beramalbaik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhCJS-kDlVBkqpTltXpj_b0Dz67qSkKik',
    appId: '1:158686991115:ios:32c094942de57187c5480e',
    messagingSenderId: '158686991115',
    projectId: 'beramalbaik-90b62',
    databaseURL: 'https://beramalbaik-90b62-default-rtdb.firebaseio.com',
    storageBucket: 'beramalbaik-90b62.firebasestorage.app',
    iosBundleId: 'com.example.beramalbaik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJhXkZFmdJ1IWFu9a6rwiqzRfKR8BIsHY',
    appId: '1:158686991115:web:f1a1a89f7cf80263c5480e',
    messagingSenderId: '158686991115',
    projectId: 'beramalbaik-90b62',
    authDomain: 'beramalbaik-90b62.firebaseapp.com',
    databaseURL: 'https://beramalbaik-90b62-default-rtdb.firebaseio.com',
    storageBucket: 'beramalbaik-90b62.firebasestorage.app',
    measurementId: 'G-10P8PL12M5',
  );
}
